name: ublue main 41
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '00 20 * * 2,4,6' 
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      fedora_version: rawhide
      akmod_version: fsync-40
